stages:
  - .pre
  - build
  - deploy

variables:
  GIT_DEPTH: 1
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - project: "hive/common-ci-configuration"
    ref: ab4d4c78df8ebc5b5d7744fe2cfa64c51143fe01
    file:
      - "/templates/npm_projects.gitlab-ci.yml"

default:
  tags:
    - public-runner-docker

lint:
  stage: .pre
  extends: .npm_based_job_base
  script:
    - pnpm lint:ci
    - pnpm format:ci

build:
  stage: build
  extends: .npm_based_job_base
  variables:
    NPM_PACKAGE_SCOPE: "@hiveio"
    NPM_PACKAGE_NAME: "components"
    NPM_REGISTRY_URL: "gitlab.syncad.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"
  needs:
    - job: lint
  script:
    - /home/emscripten/scripts/npm_generate_version.sh "${CI_PROJECT_DIR}" "${NPM_REGISTRY_URL}" "${NPM_PACKAGE_SCOPE}" "${NPM_PACKAGE_NAME}" "${COMMIT_REF_PROTECTED}" "${COMMIT_TAG}"
    - pnpm build
  artifacts:
    reports:
      dotenv:
        - "built_package_version_info.env" # contains information related to generated package version and git revision
    paths:
      - "dist"
      - "packages/*/dist"
    when: always
    expire_in: 1 week

deploy_dev_package:
  stage: deploy
  extends: .npm_deploy_package_template
  variables:
    PACKAGE_TGZ_PATH: "${BUILT_PACKAGE_PATH}"
    NPM_PACKAGE_SCOPE: "@hiveio"
  needs:
    - job: build
      artifacts: true

deploy_production_public_npm:
  stage: deploy
  extends: .registry_npmjs_org_deploy_package_template
  variables:
    NPM_PUBLISH_TOKEN: "$INTERNAL_HIDDEN_PUBLISH_TOKEN"
    NPM_PACKAGE_NAME: "components"
    PACKAGE_TGZ_PATH: "${BUILT_PACKAGE_PATH}"
  needs:
    - job: deploy_dev_package
    - job: build
      artifacts: true
